import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'dart:convert';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._();
  static LocalizationService get instance => _instance;
  LocalizationService._();

  Locale _currentLocale = const Locale('en');
  String _defaultLanguage = 'en';

  // JSON-loaded translations (from assets/lang/*.json)
  final Map<String, Map<String, String>> _jsonTranslations = {};

  Locale get currentLocale => _currentLocale;
  String get currentLanguageCode => _currentLocale.languageCode;
  String get defaultLanguage => _defaultLanguage;

  static const Map<String, String> supportedLanguages = {
    'en': 'English',
    'es': 'Español',
    'fr': 'Français',
    'pt': 'Português',
    'de': 'Deutsch',
    'ar': 'العربية',
  };

  /// Load all JSON language files from assets/lang/
  Future<void> _loadJsonTranslations() async {
    for (final code in supportedLanguages.keys) {
      try {
        final jsonStr = await rootBundle.loadString('assets/lang/$code.json');
        final Map<String, dynamic> decoded = json.decode(jsonStr);
        _jsonTranslations[code] = decoded.map(
          (k, v) => MapEntry(k, v.toString()),
        );
      } catch (_) {
        // Fallback: use in-memory translations if JSON not found
      }
    }
  }

  Future<void> initialize() async {
    await _loadJsonTranslations();

    final prefs = await SharedPreferences.getInstance();
    final savedLang = prefs.getString('preferred_language');

    if (savedLang != null && supportedLanguages.containsKey(savedLang)) {
      _currentLocale = Locale(savedLang);
    } else {
      // Auto-detect device language
      final deviceLang =
          WidgetsBinding.instance.platformDispatcher.locale.languageCode;
      if (supportedLanguages.containsKey(deviceLang)) {
        _currentLocale = Locale(deviceLang);
      } else {
        // Fallback to admin-set default
        await _loadAdminDefault();
      }
    }
    notifyListeners();
  }

  Future<void> _loadAdminDefault() async {
    try {
      final response = await Supabase.instance.client
          .from('app_settings')
          .select('setting_value')
          .eq('setting_key', 'default_language')
          .maybeSingle();
      if (response != null) {
        _defaultLanguage = response['setting_value'] as String? ?? 'en';
      }
    } catch (_) {}
    _currentLocale = Locale(_defaultLanguage);
  }

  Future<void> setLanguage(String languageCode) async {
    if (!supportedLanguages.containsKey(languageCode)) return;
    _currentLocale = Locale(languageCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('preferred_language', languageCode);

    // Save to user profile if logged in
    try {
      final userId = Supabase.instance.client.auth.currentUser?.id;
      if (userId != null) {
        await Supabase.instance.client
            .from('user_profiles')
            .update({'preferred_language': languageCode})
            .eq('id', userId);
      }
    } catch (_) {}

    notifyListeners();
  }

  /// Translate a UI/system key. Checks JSON files first, falls back to in-memory map.
  String translate(String key) {
    final lang = _currentLocale.languageCode;

    // Try JSON translations first
    if (_jsonTranslations.containsKey(lang)) {
      final val = _jsonTranslations[lang]![key];
      if (val != null) return val;
    }
    // Fallback to default language JSON
    if (_jsonTranslations.containsKey(_defaultLanguage)) {
      final val = _jsonTranslations[_defaultLanguage]![key];
      if (val != null) return val;
    }
    // Fallback to in-memory English
    if (_jsonTranslations.containsKey('en')) {
      final val = _jsonTranslations['en']![key];
      if (val != null) return val;
    }
    // Final fallback: in-memory map
    final translations = _translations[lang] ?? _translations['en']!;
    return translations[key] ?? _translations['en']![key] ?? key;
  }

  // Shorthand
  String t(String key) => translate(key);

  /// Translate admin-entered multilingual content.
  /// `translations` is a Map&lt;langCode, text&gt; stored in the DB as JSONB.
  /// Falls back to `defaultLanguage` then to `fallbackText`.
  String translateContent(
    Map<String, dynamic>? translations, {
    String fallbackText = '',
  }) {
    if (translations == null || translations.isEmpty) return fallbackText;
    final lang = _currentLocale.languageCode;

    // Try current language
    if (translations.containsKey(lang) &&
        (translations[lang] as String?)?.isNotEmpty == true) {
      return translations[lang] as String;
    }
    // Try admin default language
    if (translations.containsKey(_defaultLanguage) &&
        (translations[_defaultLanguage] as String?)?.isNotEmpty == true) {
      return translations[_defaultLanguage] as String;
    }
    // Try English
    if (translations.containsKey('en') &&
        (translations['en'] as String?)?.isNotEmpty == true) {
      return translations['en'] as String;
    }
    // Return first non-empty value
    for (final v in translations.values) {
      if (v is String && v.isNotEmpty) return v;
    }
    return fallbackText;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // Common
      'app_name': 'RoadRescue',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'delete': 'Delete',
      'edit': 'Edit',
      'close': 'Close',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'yes': 'Yes',
      'no': 'No',
      'search': 'Search',
      'filter': 'Filter',
      'all': 'All',
      'none': 'None',
      'change': 'Change',
      'not_set': 'Not set',
      'activity': 'Activity',
      'save_all': 'Save All',
      'description': 'Description',
      'language': 'Language',
      'select_language': 'Select Language',
      'language_changed': 'Language updated successfully',

      // Auth
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      'email': 'Email',
      'password': 'Password',
      'full_name': 'Full Name',
      'phone': 'Phone',
      'role': 'Role',
      'customer': 'Customer',
      'provider': 'Provider',
      'admin': 'Admin',
      'forgot_password': 'Forgot Password?',
      'already_have_account': 'Already have an account?',
      'dont_have_account': "Don't have an account?",
      'welcome_back_subtitle': 'Welcome back — help is one tap away',
      'join_subtitle': 'Join thousands of drivers and providers',
      'remember_me': 'Remember me',
      'i_am_a': 'I am a',
      'driver': 'Driver',
      'create_account': 'Create Account',
      'or_continue_with': 'Or continue with',
      'demo_credentials': 'Demo Credentials',
      'copied_to_clipboard': 'copied to clipboard',
      'generic_error': 'Something went wrong. Please try again.',
      'by_signing_up': 'By signing up, you agree to our ',
      'and': ' and ',
      'full_name_required': 'Full name is required',
      'name_too_short': 'Name must be at least 2 characters',
      'email_required': 'Email is required',
      'invalid_email': 'Enter a valid email address',
      'phone_required': 'Phone number is required',
      'password_required': 'Password is required',
      'password_too_short': 'Password must be at least 8 characters',

      // Service Request
      'request_help': 'Request Help',
      'select_service': 'Select Service Type',
      'vehicle_size': 'Vehicle Size',
      'urgency': 'Urgency',
      'standard': 'Standard',
      'urgent': 'Urgent',
      'submit_request': 'Submit Request',
      'active_request': 'Active Request',
      'searching_providers': 'Searching for providers...',
      'quote_received': 'Quote received',
      'provider_on_way': 'Provider on the way!',
      'cancel_request': 'Cancel Request',
      'whatsapp_chat': 'WhatsApp Chat',
      'what_do_you_need': 'What do you need?',
      'select_service_subtitle':
          'Select the service that matches your situation',
      'vehicle_size_subtitle': 'Select your vehicle type for accurate pricing',
      'additional_details': 'Additional Details',
      'describe_situation_hint':
          'Describe your situation (vehicle model, issue details, special instructions)…',
      'urgency_level': 'Urgency Level',
      'standard_urgency': 'Standard',
      'urgent_urgency': 'Urgent',
      'no_immediate_danger': 'No immediate danger',
      'safety_concern': 'Safety concern',
      'urgent_request_info':
          'Urgent requests are prioritized to providers. Standard response is typically 25–45 min.',
      'request_submitted': 'Request Submitted!',
      'searching_providers_info':
          "Nearby providers are being notified. You'll receive quotes within minutes.",
      'whatsapp_info_after_confirm':
          'WhatsApp chat will be available once a provider confirms your booking.',
      'track_my_request': 'Track My Request',
      'help_request_cancelled': 'Help request cancelled.',
      'detecting_location': 'Detecting your location…',
      'location_confirmed': 'Location Confirmed',
      'gps_acquiring': 'GPS is acquiring your position',
      'verified_providers_only': 'Verified providers only · Secure payment',

      // Provider
      'job_requests': 'Job Requests',
      'send_quote': 'Send Quote',
      'accept_job': 'Accept Job',
      'complete_job': 'Complete Job',
      'my_profile': 'My Profile',
      'availability': 'Availability',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'business_name': 'Business Name',
      'service_range': 'Service Range',
      'provider_dashboard': 'Provider Dashboard',
      'good_morning': 'Good morning',
      'available_at': 'Available at',
      'new_jobs': 'New Jobs',
      'active': 'Active',
      'today': 'Today',
      'no_job_requests': 'No job requests found',
      'new_jobs_info':
          'New jobs matching your services will appear here. Make sure your availability is turned on.',
      'update_services': 'Update Services',
      'select_job_detail': 'Select a job request to send a quote',
      'archive_job': 'Archive Job',
      'quote_sent_notif': 'Quote Sent',
      'on_my_way': 'On My Way',
      'navigate': 'Navigate',
      'en_route_info': 'En Route — GPS Navigation Unlocked',
      'status_updated_en_route':
          'Status updated to En Route. Customer notified!',
      'miles': 'miles',
      'performance': 'Performance',
      'jobs_done': 'Jobs Done',
      'rating': 'Rating',
      'accept_rate': 'Accept Rate',

      // Admin
      'admin_panel': 'Admin Panel',
      'categories': 'Categories',
      'geo_zones': 'Geo Zones',
      'providers': 'Providers',
      'pricing': 'Pricing',
      'transactions': 'Transactions',
      'app_config': 'App Config',
      'commission': 'Commission',
      'commission_enabled': 'Commission Enabled',
      'commission_percent': 'Commission Percentage',
      'subscription_plans': 'Subscription Plans',
      'add_plan': 'Add Plan',
      'edit_plan': 'Edit Plan',
      'plan_name': 'Plan Name',
      'monthly_price': 'Monthly Price',
      'yearly_price': 'Yearly Price',
      'trial_days': 'Trial Days',
      'discount': 'Discount',
      'features': 'Features',
      'purchase_mode': 'Purchase Mode',
      'in_app': 'In-App Purchase',
      'external_link': 'External Link',
      'external_url': 'External URL',
      'app_config_title': 'App Configuration',
      'manage_settings': 'Manage all app settings and content',
      'general_settings': 'General Settings',
      'api_keys_warning': 'API keys are sensitive. Never share them publicly.',
      'integration_keys': 'Integration Keys',
      'logo_image_url': 'Logo Image URL',
      'brand_colors': 'Brand Colors',
      'enable_slider': 'Enable Slider',
      'add_slide': 'Add Slide',
      'faq_management': 'FAQ Management',
      'language_management': 'Language Management',
      'required_documents': 'Required Provider Documents',
      'verify': 'Verify',
      'suspend': 'Suspend',
      'revenue': 'Revenue',

      // Payments
      'payment': 'Payment',
      'pay_now': 'Pay Now',
      'payment_success': 'Payment Successful!',
      'payment_failed': 'Payment Failed',
      'total_amount': 'Total Amount',
      'commission_fee': 'Platform Fee',
      'provider_receives': 'Provider Receives',
      'card_information': 'Card Information',
      'processing': 'Processing...',
      'secure_payment': 'Secure payment powered by Stripe',
      'payment_receipt': 'Payment Receipt',
      'invoice_copied': 'Invoice copied to clipboard',
      'booking_confirmed_info': 'Your booking has been confirmed',
      'download_invoice': 'Download Invoice',
      'back_to_home': 'Back to Home',
      'invoice': 'Invoice',
      'paid': 'PAID',
      'booking_ref': 'Booking Reference',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'service_provider': 'Service Provider',
      'verified': 'Verified',
      'invalid_amount': 'Invalid payment amount',
      'payment_init_failed': 'Payment initialization failed. Please try again.',
      'retry_msg': 'Retry',

      // Notifications
      'notifications': 'Notifications',
      'new_job_request': 'New Job Request',
      'quote_received_notif': 'You received a quote',
      'booking_confirmed': 'Booking Confirmed',
      'job_completed': 'Job Completed',
      'payment_received': 'Payment Received',

      // Profile
      'profile': 'Profile',
      'settings': 'Settings',
      'personal_info': 'Personal Information',
      'address': 'Address',
      'update_profile': 'Update Profile',
      'profile_updated': 'Profile updated successfully!',
      'total_requests': 'Total Requests',
      'change_password': 'Change Password',
      'customers_can_see_you': 'Customers can see and book you',
      'unavailable_info': 'You won\'t receive new requests',
      'available_msg': 'You are now available for requests',
      'unavailable_msg': 'You are now unavailable',
      'business_info': 'Business Information',
      'business_image_url': 'Business Image URL',
      'adjust_range': 'Adjust Range',
      'miles_radius': 'miles radius',
      'from_base_location': 'from your base location',

      // Subscription
      'subscription': 'Subscription',
      'current_plan': 'Current Plan',
      'upgrade_plan': 'Upgrade Plan',
      'subscribe': 'Subscribe',
      'per_month': '/month',
      'per_year': '/year',
      'free_trial': 'Free Trial',
      'days_free': 'days free',
      'most_popular': 'Most Popular',
      'view_plans': 'View Plans',

      // Multilingual content
      'faq_title': 'FAQ',
      'privacy_policy': 'Privacy Policy',
      'blog': 'Blog',
      'translations': 'Translations',
      'add_translation': 'Add Translation',
      'default_language': 'Default Language',
      'enabled_languages': 'Enabled Languages',
      'content_translations': 'Content Translations',
      'enter_translation': 'Enter translation for this language',
      'translation_saved': 'Translations saved successfully',
      'fallback_language': 'Fallback Language',
    },
    'es': {
      'app_name': 'RoadRescue',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'close': 'Cerrar',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'retry': 'Reintentar',
      'back': 'Atrás',
      'next': 'Siguiente',
      'done': 'Listo',
      'yes': 'Sí',
      'no': 'No',
      'search': 'Buscar',
      'filter': 'Filtrar',
      'all': 'Todos',
      'none': 'Ninguno',
      'change': 'Cambiar',
      'not_set': 'No establecido',
      'activity': 'Actividad',
      'save_all': 'Guardar todo',
      'description': 'Descripción',
      'language': 'Idioma',
      'select_language': 'Seleccionar Idioma',
      'language_changed': 'Idioma actualizado correctamente',
      'sign_in': 'Iniciar Sesión',
      'sign_up': 'Registrarse',
      'sign_out': 'Cerrar Sesión',
      'email': 'Correo',
      'password': 'Contraseña',
      'full_name': 'Nombre Completo',
      'phone': 'Teléfono',
      'role': 'Rol',
      'customer': 'Cliente',
      'provider': 'Proveedor',
      'admin': 'Administrador',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'already_have_account': '¿Ya tienes una cuenta?',
      'dont_have_account': '¿No tienes una cuenta?',
      'welcome_back_subtitle': 'Bienvenido de nuevo: la ayuda está a un toque',
      'join_subtitle': 'Únete a miles de conductores y proveedores',
      'remember_me': 'Recordarme',
      'i_am_a': 'Soy un',
      'driver': 'Conductor',
      'create_account': 'Crear cuenta',
      'or_continue_with': 'O continuar con',
      'demo_credentials': 'Credenciales de demostración',
      'copied_to_clipboard': 'copiado al portapapeles',
      'generic_error': 'Algo salió mal. Por favor, inténtelo de nuevo.',
      'by_signing_up': 'Al registrarte, aceptas nuestros ',
      'and': ' y ',
      'full_name_required': 'El nombre completo es obligatorio',
      'name_too_short': 'El nombre debe tener al menos 2 caracteres',
      'email_required': 'El correo es obligatorio',
      'invalid_email': 'Ingrese un correo válido',
      'phone_required': 'El número de teléfono es obligatorio',
      'password_required': 'La contraseña es obligatoria',
      'password_too_short': 'La contraseña debe tener al menos 8 caracteres',
      'request_help': 'Solicitar Ayuda',
      'select_service': 'Seleccionar Tipo de Servicio',
      'vehicle_size': 'Tamaño del Vehículo',
      'urgency': 'Urgencia',
      'standard': 'Estándar',
      'urgent': 'Urgente',
      'submit_request': 'Enviar Solicitud',
      'active_request': 'Solicitud Activa',
      'searching_providers': 'Buscando proveedores...',
      'quote_received': 'Cotización recibida',
      'provider_on_way': '¡El proveedor está en camino!',
      'cancel_request': 'Cancelar Solicitud',
      'whatsapp_chat': 'Chat de WhatsApp',
      'what_do_you_need': '¿Qué necesitas?',
      'select_service_subtitle':
          'Selecciona el servicio que mejor se adapte a tu situación',
      'vehicle_size_subtitle':
          'Selecciona el tamaño de tu vehículo para un precio exacto',
      'additional_details': 'Detalles adicionales',
      'describe_situation_hint':
          'Describe tu situación (modelo de vehículo, detalles del problema, instrucciones especiales)...',
      'urgency_level': 'Nivel de urgencia',
      'standard_urgency': 'Estándar',
      'urgent_urgency': 'Urgente',
      'no_immediate_danger': 'Sin peligro inmediato',
      'safety_concern': 'Problema de seguridad',
      'urgent_request_info':
          'Las solicitudes urgentes tienen prioridad. La respuesta estándar suele ser de 25 a 45 min.',
      'request_submitted': '¡Solicitud enviada!',
      'searching_providers_info':
          'Se está notificando a los proveedores cercanos. Recibirás cotizaciones en minutos.',
      'whatsapp_info_after_confirm':
          'El chat de WhatsApp estará disponible una vez que un proveedor confirme tu reserva.',
      'track_my_request': 'Seguir mi solicitud',
      'help_request_cancelled': 'Solicitud de ayuda cancelada.',
      'detecting_location': 'Detectando tu ubicación...',
      'location_confirmed': 'Ubicación confirmada',
      'gps_acquiring': 'El GPS está adquiriendo tu posición',
      'verified_providers_only': 'Solo proveedores verificados · Pago seguro',
      'job_requests': 'Solicitudes de Trabajo',
      'send_quote': 'Enviar Cotización',
      'accept_job': 'Aceptar Trabajo',
      'complete_job': 'Completar Trabajo',
      'my_profile': 'Mi Perfil',
      'availability': 'Disponibilidad',
      'available': 'Disponible',
      'unavailable': 'No Disponible',
      'business_name': 'Nombre del Negocio',
      'service_range': 'Rango de Servicio',
      'provider_dashboard': 'Panel del Proveedor',
      'good_morning': 'Buenos días',
      'available_at': 'Disponible en',
      'new_jobs': 'Nuevos Trabajos',
      'active': 'Activo',
      'today': 'Hoy',
      'no_job_requests': 'No se encontraron solicitudes',
      'new_jobs_info':
          'Aquí aparecerán los nuevos trabajos. Asegúrate de tener activada tu disponibilidad.',
      'update_services': 'Actualizar servicios',
      'select_job_detail':
          'Selecciona una solicitud para enviar una cotización',
      'archive_job': 'Archivar trabajo',
      'quote_sent_notif': 'Cotización enviada',
      'on_my_way': 'En camino',
      'navigate': 'Navegar',
      'en_route_info': 'En camino — Navegación GPS desbloqueada',
      'status_updated_en_route':
          'Estado actualizado a En camino. ¡Cliente notificado!',
      'miles': 'millas',
      'performance': 'Rendimiento',
      'jobs_done': 'Trabajos realizados',
      'rating': 'Calificación',
      'accept_rate': 'Tasa de aceptación',
      'admin_panel': 'Panel de Administración',
      'categories': 'Categorías',
      'geo_zones': 'Zonas Geográficas',
      'providers': 'Proveedores',
      'pricing': 'Precios',
      'transactions': 'Transacciones',
      'app_config': 'Configuración',
      'commission': 'Comisión',
      'commission_enabled': 'Comisión Habilitada',
      'commission_percent': 'Porcentaje de Comisión',
      'subscription_plans': 'Planes de Suscripción',
      'add_plan': 'Agregar Plan',
      'edit_plan': 'Editar Plan',
      'plan_name': 'Nombre del Plan',
      'monthly_price': 'Precio Mensual',
      'yearly_price': 'Precio Anual',
      'trial_days': 'Días de Prueba',
      'discount': 'Descuento',
      'features': 'Características',
      'purchase_mode': 'Modo de Compra',
      'in_app': 'Compra en App',
      'external_link': 'Enlace Externo',
      'external_url': 'URL Externa',
      'app_config_title': 'Configuración de la aplicación',
      'manage_settings': 'Gestionar todos los ajustes y contenidos',
      'general_settings': 'Ajustes generales',
      'api_keys_warning':
          'Las claves API son sensibles. No las compartas nunca públicamente.',
      'integration_keys': 'Claves de integración',
      'logo_image_url': 'URL de la imagen del logotipo',
      'brand_colors': 'Colores de marca',
      'enable_slider': 'Activar deslizador',
      'add_slide': 'Añadir diapositiva',
      'faq_management': 'Gestión de preguntas frecuentes',
      'language_management': 'Gestión de idiomas',
      'required_documents': 'Documentos requeridos del proveedor',
      'verify': 'Verificar',
      'suspend': 'Suspender',
      'revenue': 'Ingresos',
      'payment': 'Pago',
      'pay_now': 'Pagar ahora',
      'payment_success': '¡Pago exitoso!',
      'payment_failed': 'Pago fallido',
      'total_amount': 'Monto total',
      'commission_fee': 'Tarifa de la plataforma',
      'provider_receives': 'El proveedor recibe',
      'card_information': 'Información de la tarjeta',
      'processing': 'Procesando...',
      'secure_payment': 'Pago seguro con Stripe',
      'payment_receipt': 'Recibo de pago',
      'invoice_copied': 'Factura copiada al portapapeles',
      'booking_confirmed_info': 'Su reserva ha sido confirmada',
      'download_invoice': 'Descargar factura',
      'back_to_home': 'Volver al inicio',
      'invoice': 'Factura',
      'paid': 'PAGADO',
      'booking_ref': 'Referencia de la reserva',
      'subtotal': 'Subtotal',
      'tax': 'Impuestos',
      'service_provider': 'Proveedor de servicios',
      'verified': 'Verificado',
      'invalid_amount': 'Monto de pago no válido',
      'payment_init_failed':
          'Fallo al inicializar el pago. Por favor, inténtelo de nuevo.',
      'retry_msg': 'Reintentar',
      'notifications': 'Notificaciones',
      'new_job_request': 'Nueva Solicitud de Trabajo',
      'quote_received_notif': 'Recibiste una cotizaci\u00f3n',
      'booking_confirmed': 'Reserva Confirmada',
      'job_completed': 'Trabajo Completado',
      'payment_received': 'Pago Recibido',
      'profile': 'Perfil',
      'settings': 'Configuraci\u00f3n',
      'personal_info': 'Informaci\u00f3n Personal',
      'address': 'Direcci\u00f3n',
      'update_profile': 'Actualizar Perfil',
      'profile_updated': "\u00a1Perfil actualizado correctamente!",
      'total_requests': 'Total de solicitudes',
      'change_password': 'Cambiar contraseña',
      'customers_can_see_you': 'Los clientes pueden verte y reservarte',
      'unavailable_info': 'No recibirás nuevas solicitudes',
      'available_msg': 'Ahora estás disponible para recibir solicitudes',
      'unavailable_msg': 'Ahora no estás disponible',
      'business_info': 'Información del negocio',
      'business_image_url': 'URL de la imagen del negocio',
      'adjust_range': 'Ajustar rango',
      'miles_radius': 'millas de radio',
      'from_base_location': 'desde tu ubicación base',
      'subscription': 'Suscripción',
      'current_plan': 'Plan Actual',
      'upgrade_plan': 'Mejorar Plan',
      'subscribe': 'Suscribirse',
      'per_month': '/mes',
      'per_year': '/a\u00f1o',
      'free_trial': 'Prueba Gratuita',
      'days_free': 'd\u00edas gratis',
      'most_popular': 'M\u00e1s Popular',
      'view_plans': 'Ver Planes',

      'faq_title': 'Preguntas Frecuentes',
      'privacy_policy': 'Pol\u00edtica de Privacidad',
      'blog': 'Blog',
      'translations': 'Traducciones',
      'add_translation': 'Agregar Traducci\u00f3n',
      'default_language': 'Idioma Predeterminado',
      'enabled_languages': 'Idiomas Habilitados',
      'content_translations': 'Traducciones de Contenido',
      'enter_translation': 'Ingrese la traducci\u00f3n para este idioma',
      'translation_saved': 'Traducciones guardadas correctamente',
      'fallback_language': 'Idioma de Respaldo',
    },
    'fr': {
      'app_name': 'RoadRescue',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'close': 'Fermer',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'retry': 'Réessayer',
      'back': 'Retour',
      'next': 'Suivant',
      'done': 'Terminé',
      'yes': 'Oui',
      'no': 'Non',
      'search': 'Rechercher',
      'filter': 'Filtrer',
      'all': 'Tous',
      'none': 'Aucun',
      'language': 'Langue',
      'select_language': 'Sélectionner la Langue',
      'language_changed': 'Langue mise à jour avec succès',
      'sign_in': 'Se Connecter',
      'sign_up': "S'inscrire",
      'sign_out': 'Se Déconnecter',
      'email': 'Email',
      'password': 'Mot de passe',
      'full_name': 'Nom Complet',
      'phone': 'Téléphone',
      'role': 'Rôle',
      'customer': 'Client',
      'provider': 'Prestataire',
      'admin': 'Administrateur',
      'request_help': "Demander de l'Aide",
      'select_service': 'Sélectionner le Type de Service',
      'vehicle_size': 'Taille du Véhicule',
      'description': 'Description',
      'urgency': 'Urgence',
      'standard': 'Standard',
      'urgent': 'Urgent',
      'submit_request': 'Soumettre la Demande',
      'active_request': 'Demande Active',
      'searching_providers': 'Recherche de prestataires...',
      'quote_received': 'Devis reçu',
      'provider_on_way': 'Le prestataire est en route!',
      'cancel_request': 'Annuler la Demande',
      'payment': 'Paiement',
      'pay_now': 'Payer Maintenant',
      'payment_success': 'Paiement Réussi!',
      'payment_failed': 'Paiement Échoué',
      'total_amount': 'Montant Total',
      'commission_fee': 'Frais de Plateforme',
      'provider_receives': 'Le Prestataire Reçoit',
      'card_information': 'Informations de Carte',
      'processing': 'Traitement...',
      'secure_payment': 'Paiement sécurisé par Stripe',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'subscription': 'Abonnement',
      'subscribe': "S'abonner",
      'per_month': '/mois',
      'per_year': '/an',
      'free_trial': 'Essai Gratuit',
      'days_free': 'jours gratuits',
      'most_popular': 'Le Plus Populaire',
      'view_plans': 'Voir les Plans',
      'notifications': 'Notifications',
      'my_profile': 'Mon Profil',
      'job_requests': 'Demandes de Travail',
      'admin_panel': "Panneau d'Administration",
      'commission': 'Commission',
      'subscription_plans': "Plans d'Abonnement",
      'forgot_password': 'Mot de passe oublié?',
      'already_have_account': 'Vous avez déjà un compte?',
      'dont_have_account': "Vous n'avez pas de compte?",
      'faq': 'FAQ',
      'terms_of_service': "Conditions d'Utilisation",
      'privacy_policy': 'Politique de Confidentialité',
      'blog': 'Blog',
      'translations': 'Traductions',
      'add_translation': 'Ajouter une Traduction',
      'default_language': 'Langue par Défaut',
      'enabled_languages': 'Langues Activées',
      'content_translations': 'Traductions de Contenu',
      'enter_translation': 'Entrez la traduction pour cette langue',
      'translation_saved': 'Traductions enregistrées avec succès',
      'fallback_language': 'Langue de Secours',
    },
    'pt': {
      'app_name': 'RoadRescue',
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'delete': 'Excluir',
      'edit': 'Editar',
      'close': 'Fechar',
      'loading': 'Carregando...',
      'error': 'Erro',
      'success': 'Sucesso',
      'retry': 'Tentar Novamente',
      'back': 'Voltar',
      'next': 'Próximo',
      'done': 'Concluído',
      'yes': 'Sim',
      'no': 'Não',
      'search': 'Pesquisar',
      'filter': 'Filtrar',
      'all': 'Todos',
      'none': 'Nenhum',
      'language': 'Idioma',
      'select_language': 'Selecionar Idioma',
      'language_changed': 'Idioma atualizado com sucesso',
      'sign_in': 'Entrar',
      'sign_up': 'Cadastrar',
      'sign_out': 'Sair',
      'email': 'Email',
      'password': 'Senha',
      'full_name': 'Nome Completo',
      'phone': 'Telefone',
      'role': 'Função',
      'customer': 'Cliente',
      'provider': 'Prestador',
      'admin': 'Administrador',
      'request_help': 'Solicitar Ajuda',
      'select_service': 'Selecionar Tipo de Serviço',
      'vehicle_size': 'Tamanho do Veículo',
      'description': 'Descrição',
      'urgency': 'Urgência',
      'standard': 'Padrão',
      'urgent': 'Urgente',
      'submit_request': 'Enviar Solicitação',
      'active_request': 'Solicitação Ativa',
      'searching_providers': 'Procurando prestadores...',
      'quote_received': 'Cotação recebida',
      'provider_on_way': 'Prestador a caminho!',
      'cancel_request': 'Cancelar Solicitação',
      'payment': 'Pagamento',
      'pay_now': 'Pagar Agora',
      'payment_success': 'Pagamento Realizado!',
      'payment_failed': 'Pagamento Falhou',
      'total_amount': 'Valor Total',
      'commission_fee': 'Taxa da Plataforma',
      'provider_receives': 'Prestador Recebe',
      'card_information': 'Informações do Cartão',
      'processing': 'Processando...',
      'secure_payment': 'Pagamento seguro via Stripe',
      'profile': 'Perfil',
      'settings': 'Configurações',
      'subscription': 'Assinatura',
      'subscribe': 'Assinar',
      'per_month': '/mês',
      'per_year': '/ano',
      'free_trial': 'Teste Gratuito',
      'days_free': 'dias grátis',
      'most_popular': 'Mais Popular',
      'view_plans': 'Ver Planos',
      'notifications': 'Notificações',
      'my_profile': 'Meu Perfil',
      'job_requests': 'Solicitações de Trabalho',
      'admin_panel': 'Painel Admin',
      'commission': 'Comissão',
      'subscription_plans': 'Planos de Assinatura',
      'forgot_password': 'Esqueceu a senha?',
      'already_have_account': 'Já tem uma conta?',
      'dont_have_account': 'Não tem uma conta?',
      'faq': 'Perguntas Frequentes',
      'terms_of_service': 'Termos de Serviço',
      'privacy_policy': 'Política de Privacidade',
      'blog': 'Blog',
      'translations': 'Traduções',
      'add_translation': 'Adicionar Tradução',
      'default_language': 'Idioma Padrão',
      'enabled_languages': 'Idiomas Habilitados',
      'content_translations': 'Traduções de Conteúdo',
      'enter_translation': 'Digite a tradução para este idioma',
      'translation_saved': 'Traduções salvas com sucesso',
      'fallback_language': 'Idioma de Fallback',
    },
    'de': {
      'app_name': 'RoadRescue',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'confirm': 'Bestätigen',
      'delete': 'Löschen',
      'edit': 'Bearbeiten',
      'close': 'Schließen',
      'loading': 'Laden...',
      'error': 'Fehler',
      'success': 'Erfolg',
      'retry': 'Wiederholen',
      'back': 'Zurück',
      'next': 'Weiter',
      'done': 'Fertig',
      'yes': 'Ja',
      'no': 'Nein',
      'search': 'Suchen',
      'filter': 'Filtern',
      'all': 'Alle',
      'none': 'Keine',
      'language': 'Sprache',
      'select_language': 'Sprache Auswählen',
      'language_changed': 'Sprache erfolgreich aktualisiert',
      'sign_in': 'Anmelden',
      'sign_up': 'Registrieren',
      'sign_out': 'Abmelden',
      'email': 'E-Mail',
      'password': 'Passwort',
      'full_name': 'Vollständiger Name',
      'phone': 'Telefon',
      'role': 'Rolle',
      'customer': 'Kunde',
      'provider': 'Anbieter',
      'admin': 'Administrator',
      'request_help': 'Hilfe Anfordern',
      'select_service': 'Servicetyp Auswählen',
      'vehicle_size': 'Fahrzeuggröße',
      'description': 'Beschreibung',
      'urgency': 'Dringlichkeit',
      'standard': 'Standard',
      'urgent': 'Dringend',
      'submit_request': 'Anfrage Senden',
      'active_request': 'Aktive Anfrage',
      'searching_providers': 'Suche nach Anbietern...',
      'quote_received': 'Angebot erhalten',
      'provider_on_way': 'Anbieter ist unterwegs!',
      'cancel_request': 'Anfrage Abbrechen',
      'payment': 'Zahlung',
      'pay_now': 'Jetzt Bezahlen',
      'payment_success': 'Zahlung Erfolgreich!',
      'payment_failed': 'Zahlung Fehlgeschlagen',
      'total_amount': 'Gesamtbetrag',
      'commission_fee': 'Plattformgebühr',
      'provider_receives': 'Anbieter Erhält',
      'card_information': 'Karteninformationen',
      'processing': 'Verarbeitung...',
      'secure_payment': 'Sichere Zahlung über Stripe',
      'profile': 'Profil',
      'settings': 'Einstellungen',
      'subscription': 'Abonnement',
      'subscribe': 'Abonnieren',
      'per_month': '/Monat',
      'per_year': '/Jahr',
      'free_trial': 'Kostenlose Testversion',
      'days_free': 'Tage kostenlos',
      'most_popular': 'Am Beliebtesten',
      'view_plans': 'Pläne Anzeigen',
      'notifications': 'Benachrichtigungen',
      'my_profile': 'Mein Profil',
      'job_requests': 'Jobanfragen',
      'admin_panel': 'Admin-Panel',
      'commission': 'Provision',
      'subscription_plans': 'Abonnementpläne',
      'forgot_password': 'Passwort vergessen?',
      'already_have_account': 'Haben Sie bereits ein Konto?',
      'dont_have_account': 'Haben Sie kein Konto?',
      'faq': 'FAQ',
      'terms_of_service': 'Nutzungsbedingungen',
      'privacy_policy': 'Datenschutzrichtlinie',
      'blog': 'Blog',
      'translations': 'Übersetzungen',
      'add_translation': 'Übersetzung Hinzufügen',
      'default_language': 'Standardsprache',
      'enabled_languages': 'Aktivierte Sprachen',
      'content_translations': 'Inhaltsübersetzungen',
      'enter_translation': 'Übersetzung für diese Sprache eingeben',
      'translation_saved': 'Übersetzungen erfolgreich gespeichert',
      'fallback_language': 'Fallback-Sprache',
    },
    'ar': {
      'app_name': 'رود ريسكيو',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'delete': 'حذف',
      'edit': 'تعديل',
      'close': 'إغلاق',
      'loading': 'جار التحميل...',
      'error': 'خطأ',
      'success': 'نجاح',
      'retry': 'إعادة المحاولة',
      'back': 'رجوع',
      'next': 'التالي',
      'done': 'تم',
      'yes': 'نعم',
      'no': 'لا',
      'search': 'بحث',
      'filter': 'تصفية',
      'all': 'الكل',
      'none': 'لا شيء',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'language_changed': 'تم تحديث اللغة بنجاح',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'sign_out': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'full_name': 'الاسم الكامل',
      'phone': 'الهاتف',
      'role': 'الدور',
      'customer': 'عميل',
      'provider': 'مزود خدمة',
      'admin': 'مدير',
      'request_help': 'طلب مساعدة',
      'select_service': 'اختر نوع الخدمة',
      'vehicle_size': 'حجم المركبة',
      'description': 'الوصف',
      'urgency': 'الأولوية',
      'standard': 'عادي',
      'urgent': 'عاجل',
      'submit_request': 'إرسال الطلب',
      'active_request': 'الطلب النشط',
      'searching_providers': 'البحث عن مزودي الخدمة...',
      'quote_received': 'تم استلام عرض السعر',
      'provider_on_way': 'المزود في الطريق!',
      'cancel_request': 'إلغاء الطلب',
      'payment': 'الدفع',
      'pay_now': 'ادفع الآن',
      'payment_success': 'تم الدفع بنجاح!',
      'payment_failed': 'فشل الدفع',
      'total_amount': 'المبلغ الإجمالي',
      'commission_fee': 'رسوم المنصة',
      'provider_receives': 'يستلم المزود',
      'card_information': 'معلومات البطاقة',
      'processing': 'جار المعالجة...',
      'secure_payment': 'دفع آمن عبر Stripe',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'subscription': 'الاشتراك',
      'subscribe': 'اشترك',
      'per_month': '/شهر',
      'per_year': '/سنة',
      'free_trial': 'تجربة مجانية',
      'days_free': 'أيام مجانية',
      'most_popular': 'الأكثر شعبية',
      'view_plans': 'عرض الخطط',
      'notifications': 'الإشعارات',
      'my_profile': 'ملفي الشخصي',
      'job_requests': 'طلبات العمل',
      'admin_panel': 'لوحة الإدارة',
      'commission': 'العمولة',
      'subscription_plans': 'خطط الاشتراك',
      'forgot_password': 'نسيت كلمة المرور؟',
      'already_have_account': 'هل لديك حساب بالفعل؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'faq': 'الأسئلة الشائعة',
      'terms_of_service': 'شروط الخدمة',
      'privacy_policy': 'سياسة الخصوصية',
      'blog': 'المدونة',
      'translations': 'الترجمات',
      'add_translation': 'إضافة ترجمة',
      'default_language': 'اللغة الافتراضية',
      'enabled_languages': 'اللغات المفعلة',
      'content_translations': 'ترجمات المحتوى',
      'enter_translation': 'أدخل الترجمة لهذه اللغة',
      'translation_saved': 'تم حفظ الترجمات بنجاح',
      'fallback_language': 'لغة الاحتياط',
    },
  };
}
