-- Update Quintana Roo cities with full list

-- First, delete existing QR cities
DELETE FROM public.cities WHERE state = 'Quintana Roo';

-- Insert all 66 cities
WITH state_qr AS (SELECT id FROM public.states WHERE code = 'QR')
INSERT INTO public.cities (name, state, state_id) VALUES
('Akumal', 'Quintana Roo', (SELECT id FROM state_qr)),
('Alfredo V. Bonfil', 'Quintana Roo', (SELECT id FROM state_qr)),
('Álvaro Obregón', 'Quintana Roo', (SELECT id FROM state_qr)),
('Bacalar', 'Quintana Roo', (SELECT id FROM state_qr)),
('Benito Juárez', 'Quintana Roo', (SELECT id FROM state_qr)),
('Cacao', 'Quintana Roo', (SELECT id FROM state_qr)),
('Calderitas', 'Quintana Roo', (SELECT id FROM state_qr)),
('Cancún', 'Quintana Roo', (SELECT id FROM state_qr)),
('Caobas', 'Quintana Roo', (SELECT id FROM state_qr)),
('Carlos A. Madrazo', 'Quintana Roo', (SELECT id FROM state_qr)),
('Chetumal', 'Quintana Roo', (SELECT id FROM state_qr)),
('Chiquilá', 'Quintana Roo', (SELECT id FROM state_qr)),
('Chunhuhub', 'Quintana Roo', (SELECT id FROM state_qr)),
('Ciudad Chemuyil', 'Quintana Roo', (SELECT id FROM state_qr)),
('Coba', 'Quintana Roo', (SELECT id FROM state_qr)),
('Cocoyol', 'Quintana Roo', (SELECT id FROM state_qr)),
('Cozumel', 'Quintana Roo', (SELECT id FROM state_qr)),
('Dziuche', 'Quintana Roo', (SELECT id FROM state_qr)),
('Dzula', 'Quintana Roo', (SELECT id FROM state_qr)),
('El Tintal', 'Quintana Roo', (SELECT id FROM state_qr)),
('Felipe Carrillo Puerto', 'Quintana Roo', (SELECT id FROM state_qr)),
('Huay Max', 'Quintana Roo', (SELECT id FROM state_qr)),
('Huay-Pix', 'Quintana Roo', (SELECT id FROM state_qr)),
('Ignacio Zaragoza', 'Quintana Roo', (SELECT id FROM state_qr)),
('Isla Holbox', 'Quintana Roo', (SELECT id FROM state_qr)),
('Isla Mujeres', 'Quintana Roo', (SELECT id FROM state_qr)),
('Javier Rojo Gómez', 'Quintana Roo', (SELECT id FROM state_qr)),
('José María Morelos', 'Quintana Roo', (SELECT id FROM state_qr)),
('Jose Narciso Rovirosa', 'Quintana Roo', (SELECT id FROM state_qr)),
('Juan Sarabia', 'Quintana Roo', (SELECT id FROM state_qr)),
('Kancabchén', 'Quintana Roo', (SELECT id FROM state_qr)),
('Kantunilkín', 'Quintana Roo', (SELECT id FROM state_qr)),
('La Presumida', 'Quintana Roo', (SELECT id FROM state_qr)),
('La Unión', 'Quintana Roo', (SELECT id FROM state_qr)),
('Lázaro Cárdenas', 'Quintana Roo', (SELECT id FROM state_qr)),
('Leona Vicario', 'Quintana Roo', (SELECT id FROM state_qr)),
('Los Divorciados', 'Quintana Roo', (SELECT id FROM state_qr)),
('Maya Balam', 'Quintana Roo', (SELECT id FROM state_qr)),
('Morocoy', 'Quintana Roo', (SELECT id FROM state_qr)),
('Nicolás Bravo', 'Quintana Roo', (SELECT id FROM state_qr)),
('Nuevo Xcán', 'Quintana Roo', (SELECT id FROM state_qr)),
('Othón P. Blanco', 'Quintana Roo', (SELECT id FROM state_qr)),
('Playa del Carmen', 'Quintana Roo', (SELECT id FROM state_qr)),
('Polyuc', 'Quintana Roo', (SELECT id FROM state_qr)),
('Presidente Juárez', 'Quintana Roo', (SELECT id FROM state_qr)),
('Pucté', 'Quintana Roo', (SELECT id FROM state_qr)),
('Puerto Aventuras', 'Quintana Roo', (SELECT id FROM state_qr)),
('Puerto Morelos', 'Quintana Roo', (SELECT id FROM state_qr)),
('Saban', 'Quintana Roo', (SELECT id FROM state_qr)),
('Sabidos', 'Quintana Roo', (SELECT id FROM state_qr)),
('San Angel', 'Quintana Roo', (SELECT id FROM state_qr)),
('Santa Rosa Segundo', 'Quintana Roo', (SELECT id FROM state_qr)),
('Señor', 'Quintana Roo', (SELECT id FROM state_qr)),
('Sergio Butrón Casas', 'Quintana Roo', (SELECT id FROM state_qr)),
('Solidaridad', 'Quintana Roo', (SELECT id FROM state_qr)),
('Subteniente López', 'Quintana Roo', (SELECT id FROM state_qr)),
('Tepich', 'Quintana Roo', (SELECT id FROM state_qr)),
('Tihosuco', 'Quintana Roo', (SELECT id FROM state_qr)),
('Tulum', 'Quintana Roo', (SELECT id FROM state_qr)),
('Ucum', 'Quintana Roo', (SELECT id FROM state_qr)),
('X Cabil', 'Quintana Roo', (SELECT id FROM state_qr)),
('X-Hazil Sur', 'Quintana Roo', (SELECT id FROM state_qr)),
('X-pichil', 'Quintana Roo', (SELECT id FROM state_qr)),
('Xul-Ha', 'Quintana Roo', (SELECT id FROM state_qr)),
('Zacalaca', 'Quintana Roo', (SELECT id FROM state_qr));
